[package]
name = "aoc_2021"
authors = ['Josh Comer <joshjcomer@gmail.com>']
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
regex = "1.4"
lazy_static = "1.4"
cached = "0.26"
itertools = "0.10"
im = "15"
memoize = "0.1"
